//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace The_Gym
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch_Wise_Offer
    {
        public int ID { get; set; }
        public Nullable<int> GYM_ID { get; set; }
        public Nullable<int> Branch_ID { get; set; }
        public Nullable<int> Offer_ID { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
