
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace The_Gym
{

using System;
    using System.Collections.Generic;
    
public partial class Demo
{

    public int ID { get; set; }

    public Nullable<int> GYM_ID { get; set; }

    public Nullable<int> Branch_ID { get; set; }

    public string First_Name { get; set; }

    public string Last_Name { get; set; }

    public string Email_ID { get; set; }

    public string Mobile { get; set; }

    public Nullable<System.DateTime> Date { get; set; }

    public Nullable<System.DateTime> Start_Date { get; set; }

    public Nullable<int> Interested_Plane_ID { get; set; }

}

}
