
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace The_Gym
{

using System;
    using System.Collections.Generic;
    
public partial class GYM
{

    public int ID { get; set; }

    public string Name { get; set; }

    public Nullable<bool> IS_Active { get; set; }

    public Nullable<int> Plan_ID { get; set; }

}

}
