
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace The_Gym
{

using System;
    using System.Collections.Generic;
    
public partial class GYM_Plan
{

    public int ID { get; set; }

    public string Name { get; set; }

    public Nullable<decimal> Worth { get; set; }

    public string Duracation { get; set; }

    public Nullable<int> Duracation_NO { get; set; }

    public Nullable<int> Number_Of_Student { get; set; }

}

}
