//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace The_Gym
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offer
    {
        public int ID { get; set; }
        public Nullable<int> GYM_ID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public Nullable<int> Discount_Type { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
