
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace The_Gym
{

using System;
    using System.Collections.Generic;
    
public partial class Plane
{

    public int ID { get; set; }

    public Nullable<int> GYM_ID { get; set; }

    public string Name { get; set; }

    public Nullable<decimal> Worth { get; set; }

    public string Duration { get; set; }

    public Nullable<int> Duration_No { get; set; }

    public Nullable<bool> Is_Active { get; set; }

    public string GST { get; set; }

}

}
