
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace The_Gym
{

using System;
    using System.Collections.Generic;
    
public partial class Student
{

    public int ID { get; set; }

    public Nullable<int> GYM_ID { get; set; }

    public Nullable<int> Branch_ID { get; set; }

    public Nullable<int> Trainer_ID { get; set; }

    public string First_Name { get; set; }

    public string Last_Name { get; set; }

    public string Email_ID { get; set; }

    public Nullable<System.DateTime> DOB { get; set; }

    public string Building_Name { get; set; }

    public string Area { get; set; }

    public string Landmark { get; set; }

    public Nullable<int> City_ID { get; set; }

    public Nullable<int> State_ID { get; set; }

    public Nullable<int> Country_ID { get; set; }

    public Nullable<int> Pin_Code { get; set; }

    public string Mobile { get; set; }

    public string Emergency { get; set; }

    public string Occupation { get; set; }

    public string Reference { get; set; }

    public string Disease { get; set; }

    public Nullable<System.DateTime> Start_Date { get; set; }

    public Nullable<int> Current_Package_ID { get; set; }

    public string Special_Instrucation { get; set; }

    public Nullable<bool> Status { get; set; }

}

}
