//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace The_Gym
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class The_GymEntities : DbContext
    {
        public The_GymEntities()
            : base("name=The_GymEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<Branch_Wise_Equipment> Branch_Wise_Equipment { get; set; }
        public virtual DbSet<Branch_Wise_Offer> Branch_Wise_Offer { get; set; }
        public virtual DbSet<Branch_Wise_Plane> Branch_Wise_Plane { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Demo> Demoes { get; set; }
        public virtual DbSet<Equipment> Equipments { get; set; }
        public virtual DbSet<Fee> Fees { get; set; }
        public virtual DbSet<GYM> GYMs { get; set; }
        public virtual DbSet<Offer> Offers { get; set; }
        public virtual DbSet<Plane> Planes { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Trainer> Trainers { get; set; }
        public virtual DbSet<GYM_Fee> GYM_Fee { get; set; }
        public virtual DbSet<GYM_Plan> GYM_Plan { get; set; }
    }
}
